### ISSUE TITLE
Jpasskit 0.0.8

### ISSUE THREAD

**Issue by akpcnu** [drallgood/jpasskit#87] opened 2017-07-03 22:34 UTC
We are using jpasskit for quite sometime. We started seeing below exception, is something changed from Apple side or certs side? This is in OSGI environment on karaf 4.0.7

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.security.cert.CertificateException: X.509 not found
	at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:235)[:1.8.0_102]
	at de.brendamour.jpasskit.signing.PKSigningInformationUtil.loadDERCertificate(PKSigningInformationUtil.java:228)[418:wrap_file__opt_apache-karaf-4.0.7_data_kar_synergy-dependencies_de_brendamour_jpasskit_0.0.8_jpasskit-0.0.8.jar:0.0.0]
	at de.brendamour.jpasskit.signing.PKSigningInformationUtil.loadSigningInformationFromPKCS12AndIntermediateCertificate(PKSigningInformationUtil.java:92)[418:wrap_file__opt_apache-karaf-4.0.7_data_kar_synergy-dependencies_de_brendamour_jpasskit_0.0.8_jpasskit-0.0.8.jar:0.0.0]
	at com.peapod.synergy.passbook.processor.PassbookProcessor.process(PassbookProcessor.java:108)[450:com.peapod.synergy.passbook-service:1.3.0.RELEASE]
	at com.peapod.synergy.passbook.routes.pass.PassRoute.lambda$doConfigure$0(PassRoute.java:65)[450:com.peapod.synergy.passbook-service:1.3.0.RELEASE]
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:468)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:117)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:468)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)[82:org.apache.camel.camel-core:2.17.3]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)[90:org.apache.camel.camel-jms:2.17.3]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:555)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:515)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:485)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1103)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1095)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:992)[181:org.apache.servicemix.bundles.spring-jms:3.2.17.RELEASE_1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_102]
Caused by: java.security.NoSuchAlgorithmException: class configured for CertificateFactory (provider: BC) cannot be found.
	at java.security.Provider$Service.getImplClass(Provider.java:1649)[:1.8.0_102]
	at java.security.Provider$Service.newInstance(Provider.java:1592)[:1.8.0_102]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)[:1.8.0_102]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)[:1.8.0_102]
	at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:230)[:1.8.0_102]
	... 31 more
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory' because the bundle wiring for bcprov is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1539)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_102]
	at java.security.Provider$Service.getImplClass(Provider.java:1636)[:1.8.0_102]
	... 35 more

**Comment by drallgood** [comment] 2017-07-04 19:32
Hi @akpcnu

This might be a duplicate of #78 
Have you checked the WWDRCA certificate to make sure it's still valid?
Have you double checked the path to that file?

**Comment by drallgood** [comment] 2017-08-21 07:08
Closing due to missing information

**Closed by drallgood** 2017-08-21 07:08 UTC
